import type { Product } from "../types";

export const PRODUCTS_SEED_DATA: Product[] = [
  {
    id: 1,
    name: "Organic Ashwagandha Powder",
    description:
      "Premium adaptogenic herb for stress relief, energy, and hormonal balance. Sourced from organic farms in Rajasthan. 100% pure, no additives.",
    price: 299,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/organic_ashwagandha_forestheals.jpg",
    imageKey: "ashwagandha",
    stock: 150,
    ratings: 4.8,
    reviewCount: 124,
    featured: true,
    bestseller: true,
    discount: 10,
    bundleIds: [],
  },
  {
    id: 2,
    name: "Brahmi Powder",
    description:
      "Ancient brain tonic for memory, focus, and cognitive enhancement. Wildcrafted from pristine forests. Supports neural health and mental clarity.",
    price: 249,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/brahmi_forestheals.jpg",
    imageKey: "brahmi",
    stock: 120,
    ratings: 4.7,
    reviewCount: 89,
    featured: true,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 3,
    name: "Organic Moringa Powder",
    description:
      "Superfood packed with 92 nutrients, 46 antioxidants, and 36 anti-inflammatories. Boosts immunity, energy, and overall vitality.",
    price: 279,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/organic_moringa_forestheals.jpg",
    imageKey: "moringa",
    stock: 200,
    ratings: 4.9,
    reviewCount: 156,
    featured: true,
    bestseller: true,
    discount: 15,
    bundleIds: [],
  },
  {
    id: 4,
    name: "Organic Neem Powder",
    description:
      "Nature's purifier for skin, blood, and immunity. Antibacterial, antifungal, anti-inflammatory. Ideal for skin conditions and detoxification.",
    price: 199,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/multani_mitti_powder_forestheals.jpg",
    imageKey: "neem",
    stock: 180,
    ratings: 4.6,
    reviewCount: 72,
    featured: false,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 5,
    name: "Triphala Churan",
    description:
      "Classic Ayurvedic blend of Amla, Haritaki, and Bibhitaki. Best digestive tonic, gentle detox, and anti-aging formula.",
    price: 229,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/triphala_churan_forestheals.jpg",
    imageKey: "triphala",
    stock: 160,
    ratings: 4.7,
    reviewCount: 98,
    featured: true,
    bestseller: true,
    discount: 5,
    bundleIds: [],
  },
  {
    id: 6,
    name: "Organic Amla Powder",
    description:
      "Richest natural source of Vitamin C. Promotes hair growth, skin glow, immunity, and digestion. Cold-pressed, pure & potent.",
    price: 219,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/organic_amla_powder_forestheals.jpg",
    imageKey: "amla",
    stock: 175,
    ratings: 4.8,
    reviewCount: 111,
    featured: true,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 7,
    name: "Multani Mitti Powder",
    description:
      "Natural clay for deep cleansing, oil control, and glowing skin. Absorbs excess sebum, unclogs pores, and brightens complexion.",
    price: 149,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/multani_mitti_powder_forestheals.jpg",
    imageKey: "multani",
    stock: 200,
    ratings: 4.5,
    reviewCount: 67,
    featured: false,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 8,
    name: "Garam Masala",
    description:
      "Authentic blend of whole spices slow-roasted and ground fresh. Warming, aromatic, and deeply flavourful. No artificial colours or preservatives.",
    price: 179,
    category: "Seeds & Spices",
    imageUrl: "/assets/products/garam_masala_forestheals.jpg",
    imageKey: "garam_masala",
    stock: 130,
    ratings: 4.7,
    reviewCount: 54,
    featured: false,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 9,
    name: "Chia Seeds",
    description:
      "Omega-3 rich superfood for weight management, energy, and gut health. High in fibre, protein, and essential minerals.",
    price: 259,
    category: "Seeds & Spices",
    imageUrl: "/assets/products/chia_seeds_forestheals.jpg",
    imageKey: "chia_seeds",
    stock: 140,
    ratings: 4.6,
    reviewCount: 83,
    featured: true,
    bestseller: false,
    discount: 10,
    bundleIds: [],
  },
  {
    id: 10,
    name: "Cloves",
    description:
      "Premium whole cloves with intense aroma. Natural analgesic, antimicrobial, and digestive aid. Sustainably sourced from Kerala spice gardens.",
    price: 189,
    category: "Seeds & Spices",
    imageUrl: "/assets/products/cloves_forestheals.jpg",
    imageKey: "cloves",
    stock: 110,
    ratings: 4.8,
    reviewCount: 46,
    featured: false,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 11,
    name: "Shatavari Powder",
    description:
      "Queen of herbs for women's wellness, hormonal balance, and lactation support. Cooling, nourishing, rejuvenating adaptogen.",
    price: 349,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/satavari_forestheals.jpg",
    imageKey: "shatavari",
    stock: 90,
    ratings: 4.9,
    reviewCount: 78,
    featured: true,
    bestseller: true,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 12,
    name: "Cardamom",
    description:
      "Finest green cardamom pods with sweet, complex aroma. Digestive tonic, breath freshener, and heart health supporter.",
    price: 299,
    category: "Seeds & Spices",
    imageUrl: "/assets/products/cardamom_forestheals.jpg",
    imageKey: "cardamom",
    stock: 95,
    ratings: 4.7,
    reviewCount: 39,
    featured: false,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 13,
    name: "Mulethi Powder",
    description:
      "Natural licorice root for sore throat, cough, acidity, and skin brightening. Sweet, soothing, and deeply healing.",
    price: 219,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/tulsi_powder_forestheals.jpg",
    imageKey: "mulethi",
    stock: 120,
    ratings: 4.6,
    reviewCount: 55,
    featured: false,
    bestseller: false,
    discount: 5,
    bundleIds: [],
  },
  {
    id: 14,
    name: "Sunflower Seeds",
    description:
      "Nutrient-dense seeds rich in Vitamin E, healthy fats, and antioxidants. Perfect for snacking, salads, and smoothies.",
    price: 199,
    category: "Seeds & Spices",
    imageUrl: "/assets/products/sunflower_seeds_forestheals.jpg",
    imageKey: "sunflower_seeds",
    stock: 160,
    ratings: 4.5,
    reviewCount: 43,
    featured: false,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 15,
    name: "Dry Ginger Powder",
    description:
      "Hot, pungent, and warming. Relieves nausea, improves digestion, boosts circulation, and supports respiratory health.",
    price: 159,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/dry_ginger_forestheals.jpg",
    imageKey: "dry_ginger",
    stock: 190,
    ratings: 4.7,
    reviewCount: 67,
    featured: false,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 16,
    name: "Tulsi Powder",
    description:
      "Holy basil — adaptogen, immunomodulator, and spiritual herb. Relieves stress, protects liver, and supports respiratory wellness.",
    price: 179,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/tulsi_powder_forestheals.jpg",
    imageKey: "tulsi",
    stock: 155,
    ratings: 4.8,
    reviewCount: 91,
    featured: false,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 17,
    name: "Turmeric Powder",
    description:
      "Golden spice with powerful curcumin. Anti-inflammatory, antioxidant, and immunity booster. Pure, vibrant haldi from certified farms.",
    price: 169,
    category: "Ayurvedic Powders",
    imageUrl: "/assets/products/turmeric_forestheals.jpg",
    imageKey: "turmeric",
    stock: 180,
    ratings: 4.8,
    reviewCount: 102,
    featured: true,
    bestseller: true,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 18,
    name: "Tej Patta (Bay Leaf)",
    description:
      "Aromatic bay leaves for culinary and medicinal use. Anti-inflammatory, digestive, and blood sugar regulating properties.",
    price: 129,
    category: "Seeds & Spices",
    imageUrl: "/assets/products/tej_patta_forestheals.jpg",
    imageKey: "tej_patta",
    stock: 210,
    ratings: 4.4,
    reviewCount: 29,
    featured: false,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 19,
    name: "Cinnamon Powder",
    description:
      "True Ceylon cinnamon, not cassia. Blood sugar regulation, anti-inflammatory, and warming digestive tonic. Sweet and deeply aromatic.",
    price: 249,
    category: "Seeds & Spices",
    imageUrl: "/assets/products/cinnamon_forestheals.jpg",
    imageKey: "cinnamon",
    stock: 130,
    ratings: 4.7,
    reviewCount: 62,
    featured: true,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 20,
    name: "Pumpkin Seeds",
    description:
      "Zinc, magnesium, and omega-3 rich seeds for prostate health, sleep quality, and immune function. Lightly roasted, full-flavoured.",
    price: 229,
    category: "Seeds & Spices",
    imageUrl: "/assets/products/pumpkin_seeds_forestheals.jpg",
    imageKey: "pumpkin_seeds",
    stock: 145,
    ratings: 4.6,
    reviewCount: 51,
    featured: false,
    bestseller: false,
    discount: 0,
    bundleIds: [],
  },
];
