import type { Product } from "../types";

export const PRODUCTS_SEED_DATA: Product[] = [
  {
    id: 1,
    name: "Organic Ashwagandha Powder",
    description:
      "Premium adaptogenic herb for stress relief, energy, and hormonal balance. Sourced from organic farms in Rajasthan. 100% pure, no additives.",
    price: 299,
    category: "Ayurvedic Powders",
    imageUrl:
      "https://images.unsplash.com/photo-1611485988300-b7ef6f928b24?w=400&q=80",
    imageKey: "ashwagandha",
    stock: 150,
    ratings: 4.8,
    reviewCount: 124,
    featured: true,
    discount: 10,
    bundleIds: [],
  },
  {
    id: 2,
    name: "Brahmi Powder",
    description:
      "Ancient brain tonic for memory, focus, and cognitive enhancement. Wildcrafted from pristine forests. Supports neural health and mental clarity.",
    price: 249,
    category: "Ayurvedic Powders",
    imageUrl:
      "/assets/products/brahmi_forestheals_1-019d9662-2c41-75bc-a5b8-eb510ab47ee9.jpg",
    imageKey: "brahmi",
    stock: 120,
    ratings: 4.7,
    reviewCount: 89,
    featured: true,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 3,
    name: "Organic Moringa Powder",
    description:
      "Superfood packed with 92 nutrients, 46 antioxidants, and 36 anti-inflammatories. Boosts immunity, energy, and overall vitality.",
    price: 279,
    category: "Ayurvedic Powders",
    imageUrl:
      "https://images.unsplash.com/photo-1542848284-8afa78a08ccb?w=400&q=80",
    imageKey: "moringa",
    stock: 200,
    ratings: 4.9,
    reviewCount: 156,
    featured: true,
    discount: 15,
    bundleIds: [],
  },
  {
    id: 4,
    name: "Organic Neem Powder",
    description:
      "Nature's purifier for skin, blood, and immunity. Antibacterial, antifungal, anti-inflammatory. Ideal for skin conditions and detoxification.",
    price: 199,
    category: "Ayurvedic Powders",
    imageUrl:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    imageKey: "neem",
    stock: 180,
    ratings: 4.6,
    reviewCount: 72,
    featured: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 5,
    name: "Triphala Churan",
    description:
      "Classic Ayurvedic blend of Amla, Haritaki, and Bibhitaki. Best digestive tonic, gentle detox, and anti-aging formula.",
    price: 229,
    category: "Ayurvedic Powders",
    imageUrl:
      "https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=400&q=80",
    imageKey: "triphala",
    stock: 160,
    ratings: 4.7,
    reviewCount: 98,
    featured: true,
    discount: 5,
    bundleIds: [],
  },
  {
    id: 6,
    name: "Organic Amla Powder",
    description:
      "Richest natural source of Vitamin C. Promotes hair growth, skin glow, immunity, and digestion. Cold-pressed, pure & potent.",
    price: 219,
    category: "Ayurvedic Powders",
    imageUrl:
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    imageKey: "amla",
    stock: 175,
    ratings: 4.8,
    reviewCount: 111,
    featured: true,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 7,
    name: "Multani Mitti Powder",
    description:
      "Natural clay for deep cleansing, oil control, and glowing skin. Absorbs excess sebum, unclogs pores, and brightens complexion.",
    price: 149,
    category: "Ayurvedic Powders",
    imageUrl:
      "https://images.unsplash.com/photo-1631704698769-5e9ce9c98f98?w=400&q=80",
    imageKey: "multani",
    stock: 200,
    ratings: 4.5,
    reviewCount: 67,
    featured: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 8,
    name: "Garam Masala",
    description:
      "Authentic blend of whole spices slow-roasted and ground fresh. Warming, aromatic, and deeply flavourful. No artificial colours or preservatives.",
    price: 179,
    category: "Seeds & Spices",
    imageUrl:
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    imageKey: "garam_masala",
    stock: 130,
    ratings: 4.7,
    reviewCount: 54,
    featured: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 9,
    name: "Chia Seeds",
    description:
      "Omega-3 rich superfood for weight management, energy, and gut health. High in fibre, protein, and essential minerals.",
    price: 259,
    category: "Seeds & Spices",
    imageUrl:
      "https://images.unsplash.com/photo-1582515073490-39981397c445?w=400&q=80",
    imageKey: "chia_seeds",
    stock: 140,
    ratings: 4.6,
    reviewCount: 83,
    featured: true,
    discount: 10,
    bundleIds: [],
  },
  {
    id: 10,
    name: "Cloves",
    description:
      "Premium whole cloves with intense aroma. Natural analgesic, antimicrobial, and digestive aid. Sustainably sourced from Kerala spice gardens.",
    price: 189,
    category: "Seeds & Spices",
    imageUrl:
      "/assets/products/cloves_forestheals_1-019d9662-2c47-771f-87f4-0c6fdde85069.jpg",
    imageKey: "cloves",
    stock: 110,
    ratings: 4.8,
    reviewCount: 46,
    featured: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 11,
    name: "Shatavari Powder",
    description:
      "Queen of herbs for women's wellness, hormonal balance, and lactation support. Cooling, nourishing, rejuvenating adaptogen.",
    price: 349,
    category: "Ayurvedic Powders",
    imageUrl:
      "/assets/products/satavari_forestheals_1-019d9662-2c7c-7462-8db5-4fd3a37c660b.jpg",
    imageKey: "shatavari",
    stock: 90,
    ratings: 4.9,
    reviewCount: 78,
    featured: true,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 12,
    name: "Cardamom",
    description:
      "Finest green cardamom pods with sweet, complex aroma. Digestive tonic, breath freshener, and heart health supporter.",
    price: 299,
    category: "Seeds & Spices",
    imageUrl:
      "/assets/products/cardamom_forestheals_1-019d9662-2cdf-7169-8205-fa46e0f05b04.jpg",
    imageKey: "cardamom",
    stock: 95,
    ratings: 4.7,
    reviewCount: 39,
    featured: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 13,
    name: "Mulethi Powder",
    description:
      "Natural licorice root for sore throat, cough, acidity, and skin brightening. Sweet, soothing, and deeply healing.",
    price: 219,
    category: "Ayurvedic Powders",
    imageUrl:
      "/assets/products/mulethi_forestheals_1-019d9662-2d26-7704-9f21-4f4a46faca96.jpg",
    imageKey: "mulethi",
    stock: 120,
    ratings: 4.6,
    reviewCount: 55,
    featured: false,
    discount: 5,
    bundleIds: [],
  },
  {
    id: 14,
    name: "Sunflower Seeds",
    description:
      "Nutrient-dense seeds rich in Vitamin E, healthy fats, and antioxidants. Perfect for snacking, salads, and smoothies.",
    price: 199,
    category: "Seeds & Spices",
    imageUrl:
      "https://images.unsplash.com/photo-1616391182219-e080b4d1043a?w=400&q=80",
    imageKey: "sunflower_seeds",
    stock: 160,
    ratings: 4.5,
    reviewCount: 43,
    featured: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 15,
    name: "Dry Ginger Powder",
    description:
      "Hot, pungent, and warming. Relieves nausea, improves digestion, boosts circulation, and supports respiratory health.",
    price: 159,
    category: "Ayurvedic Powders",
    imageUrl:
      "/assets/products/dry_ginger_forestheals-019d9662-2d3d-77ce-8673-04553a7fe9be.jpg",
    imageKey: "dry_ginger",
    stock: 190,
    ratings: 4.7,
    reviewCount: 67,
    featured: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 16,
    name: "Tulsi Powder",
    description:
      "Holy basil — adaptogen, immunomodulator, and spiritual herb. Relieves stress, protects liver, and supports respiratory wellness.",
    price: 179,
    category: "Ayurvedic Powders",
    imageUrl:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    imageKey: "tulsi",
    stock: 155,
    ratings: 4.8,
    reviewCount: 91,
    featured: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 17,
    name: "Sesame Seeds",
    description:
      "White sesame seeds rich in calcium, iron, and healthy fats. Supports bone health, skin nourishment, and heart wellness.",
    price: 169,
    category: "Seeds & Spices",
    imageUrl:
      "https://images.unsplash.com/photo-1616391182219-e080b4d1043a?w=400&q=80",
    imageKey: "sesame_seeds",
    stock: 180,
    ratings: 4.5,
    reviewCount: 38,
    featured: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 18,
    name: "Tej Patta (Bay Leaf)",
    description:
      "Aromatic bay leaves for culinary and medicinal use. Anti-inflammatory, digestive, and blood sugar regulating properties.",
    price: 129,
    category: "Seeds & Spices",
    imageUrl:
      "/assets/products/tej_patta_forestheals_1-019d9662-2fc8-7000-abd2-43f604694f2f.jpg",
    imageKey: "tej_patta",
    stock: 210,
    ratings: 4.4,
    reviewCount: 29,
    featured: false,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 19,
    name: "Cinnamon Powder",
    description:
      "True Ceylon cinnamon, not cassia. Blood sugar regulation, anti-inflammatory, and warming digestive tonic. Sweet and deeply aromatic.",
    price: 249,
    category: "Seeds & Spices",
    imageUrl:
      "/assets/products/cinnamon_1-019d9662-2c73-768d-b29f-7e504b14299c.jpg",
    imageKey: "cinnamon",
    stock: 130,
    ratings: 4.7,
    reviewCount: 62,
    featured: true,
    discount: 0,
    bundleIds: [],
  },
  {
    id: 20,
    name: "Pumpkin Seeds",
    description:
      "Zinc, magnesium, and omega-3 rich seeds for prostate health, sleep quality, and immune function. Lightly roasted, full-flavoured.",
    price: 229,
    category: "Seeds & Spices",
    imageUrl:
      "https://images.unsplash.com/photo-1582515073490-39981397c445?w=400&q=80",
    imageKey: "pumpkin_seeds",
    stock: 145,
    ratings: 4.6,
    reviewCount: 51,
    featured: false,
    discount: 0,
    bundleIds: [],
  },
];
