/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityType = { 'Login' : null } |
  { 'WishlistRemove' : null } |
  { 'CouponUsed' : null } |
  { 'OrderPlaced' : null } |
  { 'ProductView' : null } |
  { 'Logout' : null } |
  { 'NewsletterSignup' : null } |
  { 'ProfileUpdated' : null } |
  { 'CartAdd' : null } |
  { 'SearchQuery' : null } |
  { 'ReviewSubmitted' : null } |
  { 'WishlistAdd' : null } |
  { 'B2BInquiry' : null } |
  { 'CartRemove' : null } |
  { 'AddressAdded' : null };
export interface AddReviewInput {
  'text' : string,
  'productId' : bigint,
  'rating' : bigint,
}
export interface Address {
  'id' : string,
  'tag' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'fullName' : string,
  'state' : string,
  'isDefault' : boolean,
  'phone' : string,
  'pincode' : string,
}
export interface Address__1 {
  'country' : string,
  'gstNumber' : [] | [string],
  'city' : string,
  'fullName' : string,
  'line1' : string,
  'line2' : [] | [string],
  'state' : string,
  'phone' : string,
  'pincode' : string,
}
export interface AdminCoupon {
  'id' : string,
  'minCartValue' : bigint,
  'active' : boolean,
  'discountValue' : bigint,
  'expiresAt' : [] | [bigint],
  'code' : string,
  'createdAt' : bigint,
  'discountType' : string,
  'usedCount' : bigint,
  'description' : string,
  'maxUses' : bigint,
}
export interface AdminExpense {
  'id' : string,
  'date' : bigint,
  'createdBy' : string,
  'description' : string,
  'category' : string,
  'amount' : bigint,
}
export type AdminLoginResult = { 'ok' : boolean } |
  { 'err' : string };
export interface AdminNotification {
  'id' : string,
  'notificationType' : string,
  'createdAt' : bigint,
  'read' : boolean,
  'message' : string,
}
export interface AdminStats {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'totalRevenue' : bigint,
}
export interface AdminTask {
  'id' : string,
  'title' : string,
  'assignedTo' : [] | [string],
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'description' : string,
  'notes' : string,
  'category' : string,
  'priority' : string,
}
export interface AnalyticsSummary {
  'revenueByDay' : Array<DayRevenue>,
  'totalExpenses' : bigint,
  'orderCount' : bigint,
  'paymentBreakdown' : PaymentBreakdown,
  'revenueByMonth' : Array<MonthRevenue>,
  'topProducts' : Array<TopProduct>,
  'customerCount' : bigint,
  'totalRevenue' : bigint,
  'avgOrderValue' : bigint,
  'netProfit' : bigint,
}
export interface B2BInquiry {
  'id' : bigint,
  'contactName' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'productInterest' : string,
  'companyName' : string,
  'quantity' : string,
  'phone' : string,
}
export interface B2BInquiryInput {
  'contactName' : string,
  'email' : string,
  'message' : string,
  'productInterest' : string,
  'companyName' : string,
  'quantity' : string,
  'phone' : string,
}
export interface BlogPost {
  'id' : string,
  'metaDescription' : string,
  'status' : string,
  'title' : string,
  'content' : string,
  'publishDate' : [] | [bigint],
  'featuredImage' : string,
  'createdAt' : bigint,
  'slug' : string,
  'tags' : Array<string>,
  'updatedAt' : bigint,
  'metaTitle' : string,
  'excerpt' : string,
}
export interface CartItem {
  'productId' : bigint,
  'productType' : [] | [string],
  'quantity' : bigint,
  'price' : bigint,
}
export type Category = string;
export interface Coupon {
  'active' : boolean,
  'expiryDate' : bigint,
  'code' : string,
  'usedCount' : bigint,
  'discountPercent' : bigint,
  'maxUses' : bigint,
}
export interface CouponValidation {
  'valid' : boolean,
  'discountPercent' : bigint,
  'message' : string,
}
export interface CreateCouponInput {
  'expiryDate' : bigint,
  'code' : string,
  'discountPercent' : bigint,
  'maxUses' : bigint,
}
export interface CreateFlashSaleInput {
  'startTime' : bigint,
  'endTime' : bigint,
  'discountPercent' : bigint,
  'productId' : bigint,
}
export interface CreateOrderInput {
  'couponCode' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'userId' : [] | [string],
  'addressId' : [] | [string],
  'address' : Address__1,
  'notes' : [] | [string],
  'stripePaymentId' : [] | [string],
  'items' : Array<CartItem>,
}
export interface CreateProductInput {
  'status' : ProductStatus,
  'featured' : boolean,
  'bundleIds' : Array<bigint>,
  'name' : string,
  'description' : string,
  'comparePrice' : [] | [bigint],
  'stock' : bigint,
  'imageKey' : string,
  'imageUrl' : string,
  'discount' : bigint,
  'category' : Category,
  'price' : bigint,
  'bestseller' : boolean,
  'images' : Array<string>,
}
export interface DashboardKPIs {
  'totalProducts' : bigint,
  'weekOrders' : bigint,
  'totalOrders' : bigint,
  'pendingOrderCount' : bigint,
  'monthOrders' : bigint,
  'monthRevenue' : bigint,
  'lowStockCount' : bigint,
  'pendingReviewCount' : bigint,
  'todayRevenue' : bigint,
  'totalRevenue' : bigint,
  'totalCustomers' : bigint,
  'weekRevenue' : bigint,
  'todayOrders' : bigint,
}
export interface DayRevenue {
  'revenue' : bigint,
  'date' : string,
  'orders' : bigint,
}
export interface EnrichedCustomerProfile {
  'id' : Principal,
  'status' : string,
  'totalOrders' : bigint,
  'country' : string,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'state' : string,
  'totalSpend' : bigint,
  'addresses' : Array<Address>,
  'phone' : string,
  'pincode' : string,
  'lastLogin' : [] | [bigint],
  'activityCount' : bigint,
}
export interface FlashSale {
  'id' : bigint,
  'startTime' : bigint,
  'active' : boolean,
  'endTime' : bigint,
  'discountPercent' : bigint,
  'productId' : bigint,
}
export interface InventoryItem {
  'supplierContact' : string,
  'lowStockThreshold' : bigint,
  'purchaseCost' : bigint,
  'expiryDate' : [] | [bigint],
  'supplierName' : string,
  'lastUpdated' : bigint,
  'productId' : string,
  'incomingStock' : bigint,
  'reservedStock' : bigint,
  'batchNumber' : string,
  'currentStock' : bigint,
  'damagedStock' : bigint,
}
export interface InventorySummaryItem {
  'outOfStockFlag' : boolean,
  'productId' : bigint,
  'productName' : string,
  'reservedStock' : bigint,
  'availableStock' : bigint,
  'lowStockFlag' : boolean,
}
export interface MonthRevenue {
  'month' : string,
  'revenue' : bigint,
  'orders' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'couponCode' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'userId' : Principal,
  'discountAmount' : bigint,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'totalAmount' : bigint,
  'address' : Address__1,
  'notes' : [] | [string],
  'stripePaymentId' : [] | [string],
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'processing' : null };
export interface PaymentBreakdown {
  'onlineCount' : bigint,
  'onlineAmount' : bigint,
  'codAmount' : bigint,
  'codCount' : bigint,
}
export type PaymentMethod = { 'cod' : null } |
  { 'stripe' : null };
export interface Product {
  'id' : bigint,
  'status' : ProductStatus,
  'featured' : boolean,
  'bundleIds' : Array<bigint>,
  'name' : string,
  'ratings' : number,
  'description' : string,
  'comparePrice' : [] | [bigint],
  'stock' : bigint,
  'imageKey' : string,
  'imageUrl' : string,
  'discount' : bigint,
  'category' : Category,
  'price' : bigint,
  'bestseller' : boolean,
  'reviewCount' : bigint,
  'images' : Array<string>,
}
export interface ProductFilter {
  'status' : [] | [ProductStatus],
  'featured' : [] | [boolean],
  'minRating' : [] | [number],
  'sortBy' : [] | [string],
  'maxPrice' : [] | [bigint],
  'category' : [] | [string],
  'minPrice' : [] | [bigint],
  'searchQuery' : [] | [string],
}
export type ProductStatus = { 'active' : null } |
  { 'inactive' : null } |
  { 'draft' : null };
export interface RegisterUserInput {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface Review {
  'id' : bigint,
  'verified' : boolean,
  'userId' : Principal,
  'createdAt' : bigint,
  'text' : string,
  'productId' : bigint,
  'approved' : boolean,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StoreSettings {
  'timezone' : string,
  'seoTitle' : string,
  'gstNumber' : string,
  'freeShippingThreshold' : bigint,
  'instagramUrl' : string,
  'whatsappNumber' : string,
  'logoUrl' : string,
  'currency' : string,
  'storeName' : string,
  'contactEmail' : string,
  'shippingDefault' : bigint,
  'gstRate' : bigint,
  'seoDescription' : string,
  'faviconUrl' : string,
  'facebookUrl' : string,
  'contactPhone' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TeamMember {
  'id' : string,
  'permissions' : Array<string>,
  'active' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'email' : string,
}
export interface TopProduct {
  'revenue' : bigint,
  'productId' : bigint,
  'unitsSold' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateUserInput {
  'country' : string,
  'city' : string,
  'name' : string,
  'email' : string,
  'state' : string,
  'addresses' : Array<Address>,
  'phone' : string,
  'pincode' : string,
}
export interface UserActivity {
  'id' : bigint,
  'activityType' : ActivityType,
  'metadata' : string,
  'userId' : Principal,
  'timestamp' : bigint,
}
export interface UserProfile {
  'id' : Principal,
  'country' : string,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'state' : string,
  'addresses' : Array<Address>,
  'phone' : string,
  'pincode' : string,
  'phoneVerified' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addExpense' : ActorMethod<[AdminExpense], AdminExpense>,
  'addReview' : ActorMethod<[AddReviewInput], Review>,
  'addTeamMember' : ActorMethod<[TeamMember], TeamMember>,
  'addToCart' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'adminListProducts' : ActorMethod<[], Array<Product>>,
  'approveReview' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[bigint], boolean>,
  'clearAllNotifications' : ActorMethod<[], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'completeAdminTask' : ActorMethod<[string], boolean>,
  'createAdminCoupon' : ActorMethod<[AdminCoupon], AdminCoupon>,
  'createAdminTask' : ActorMethod<[AdminTask], AdminTask>,
  'createBlogPost' : ActorMethod<[BlogPost], BlogPost>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCoupon' : ActorMethod<[CreateCouponInput], Coupon>,
  'createFlashSale' : ActorMethod<[CreateFlashSaleInput], FlashSale>,
  'createOrder' : ActorMethod<[CreateOrderInput], Order>,
  'createProduct' : ActorMethod<[CreateProductInput], Product>,
  'createReview' : ActorMethod<[AddReviewInput], Review>,
  'createTask' : ActorMethod<[AdminTask], AdminTask>,
  'deactivateFlashSale' : ActorMethod<[bigint], boolean>,
  'deleteAdminCoupon' : ActorMethod<[string], boolean>,
  'deleteAdminTask' : ActorMethod<[string], boolean>,
  'deleteBlogPost' : ActorMethod<[string], boolean>,
  'deleteCoupon' : ActorMethod<[string], boolean>,
  'deleteExpense' : ActorMethod<[string], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'deleteTask' : ActorMethod<[string], boolean>,
  'deleteTeamMember' : ActorMethod<[string], boolean>,
  'endFlashSale' : ActorMethod<[bigint], boolean>,
  'getActiveFlashSales' : ActorMethod<[], Array<FlashSale>>,
  'getAdminCoupons' : ActorMethod<[], Array<AdminCoupon>>,
  'getAdminNotifications' : ActorMethod<[], Array<AdminNotification>>,
  'getAdminSession' : ActorMethod<[], boolean>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAdminTasks' : ActorMethod<[], Array<AdminTask>>,
  'getAllActivities' : ActorMethod<[], Array<UserActivity>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllCustomers' : ActorMethod<[], Array<UserProfile>>,
  'getAllCustomersEnriched' : ActorMethod<[], Array<EnrichedCustomerProfile>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'totalOrders' : bigint,
      'totalActivities' : bigint,
      'newUsersToday' : bigint,
      'recentActivities' : Array<UserActivity>,
      'activeUsersToday' : bigint,
      'totalRegisteredUsers' : bigint,
      'totalExpenses' : bigint,
      'totalRevenue' : bigint,
      'totalCustomers' : bigint,
      'avgOrderValue' : bigint,
      'netProfit' : bigint,
    }
  >,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getB2BInquiries' : ActorMethod<[], Array<B2BInquiry>>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCoupons' : ActorMethod<[], Array<Coupon>>,
  'getCustomerProfile' : ActorMethod<
    [Principal],
    [] | [EnrichedCustomerProfile]
  >,
  'getDashboardKPIs' : ActorMethod<[], DashboardKPIs>,
  'getExpenses' : ActorMethod<[], Array<AdminExpense>>,
  'getExpensesByCategory' : ActorMethod<[], Array<[string, bigint]>>,
  'getInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getInventorySummary' : ActorMethod<[], Array<InventorySummaryItem>>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getNewsletterSubscribers' : ActorMethod<[], Array<string>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductReviews' : ActorMethod<[bigint], Array<Review>>,
  'getProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'getRecentActivity' : ActorMethod<[], Array<UserActivity>>,
  'getRecommendations' : ActorMethod<[string], Array<Product>>,
  'getStoreSettings' : ActorMethod<[], StoreSettings>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTasks' : ActorMethod<[], Array<AdminTask>>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getUserActivities' : ActorMethod<[[] | [Principal]], Array<UserActivity>>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<bigint>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isWishlisted' : ActorMethod<[bigint], boolean>,
  'listAllOrders' : ActorMethod<[], Array<Order>>,
  'listB2BInquiries' : ActorMethod<[], Array<B2BInquiry>>,
  'listBundles' : ActorMethod<[], Array<Product>>,
  'listEmails' : ActorMethod<[], Array<string>>,
  'listFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'listUserOrders' : ActorMethod<[], Array<Order>>,
  'logUserActivity' : ActorMethod<[ActivityType, string], UserActivity>,
  'markNotificationRead' : ActorMethod<[string], boolean>,
  'placeOrder' : ActorMethod<[CreateOrderInput], Order>,
  'publishBlogPost' : ActorMethod<[string], boolean>,
  'redeemCoupon' : ActorMethod<[string], boolean>,
  'registerUser' : ActorMethod<[RegisterUserInput], UserProfile>,
  'rejectReview' : ActorMethod<[bigint], boolean>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'removeTeamMember' : ActorMethod<[string], boolean>,
  'saveStoreSettings' : ActorMethod<[StoreSettings], StoreSettings>,
  'seedProducts' : ActorMethod<[], undefined>,
  'setAdminPassword' : ActorMethod<[string], AdminLoginResult>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'submitB2BInquiry' : ActorMethod<[B2BInquiryInput], B2BInquiry>,
  'subscribeEmail' : ActorMethod<[string], boolean>,
  'subscribeNewsletter' : ActorMethod<[string, string], boolean>,
  'toggleBestseller' : ActorMethod<[bigint], boolean>,
  'toggleCouponActive' : ActorMethod<[string], boolean>,
  'toggleFeatured' : ActorMethod<[bigint], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminCoupon' : ActorMethod<[string, AdminCoupon], [] | [AdminCoupon]>,
  'updateAdminTask' : ActorMethod<[string, AdminTask], [] | [AdminTask]>,
  'updateBlogPost' : ActorMethod<[string, BlogPost], [] | [BlogPost]>,
  'updateCartQuantity' : ActorMethod<[bigint, bigint], undefined>,
  'updateExpense' : ActorMethod<[string, AdminExpense], [] | [AdminExpense]>,
  'updateInventory' : ActorMethod<
    [string, bigint, string, string],
    [] | [InventoryItem]
  >,
  'updateInventoryStock' : ActorMethod<
    [string, bigint, string],
    [] | [InventoryItem]
  >,
  'updateOrderNotes' : ActorMethod<[bigint, [] | [string]], boolean>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], boolean>,
  'updateProduct' : ActorMethod<[bigint, CreateProductInput], boolean>,
  'updateStoreSettings' : ActorMethod<[StoreSettings], StoreSettings>,
  'updateTask' : ActorMethod<[string, AdminTask], [] | [AdminTask]>,
  'updateTeamMember' : ActorMethod<[string, TeamMember], [] | [TeamMember]>,
  'updateUserProfile' : ActorMethod<[UpdateUserInput], [] | [UserProfile]>,
  'upsertInventoryItem' : ActorMethod<[InventoryItem], InventoryItem>,
  'validateCoupon' : ActorMethod<[string], CouponValidation>,
  'verifyAdminCredentials' : ActorMethod<[string, string], AdminLoginResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];