/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddReviewInput {
  'text' : string,
  'productId' : bigint,
  'rating' : bigint,
}
export interface Address {
  'street' : string,
  'country' : string,
  'gstNumber' : [] | [string],
  'city' : string,
  'postalCode' : string,
  'state' : string,
}
export interface AdminCoupon {
  'id' : string,
  'minCartValue' : bigint,
  'active' : boolean,
  'discountValue' : bigint,
  'expiresAt' : [] | [bigint],
  'code' : string,
  'createdAt' : bigint,
  'discountType' : string,
  'usedCount' : bigint,
  'description' : string,
  'maxUses' : bigint,
}
export interface AdminExpense {
  'id' : string,
  'date' : bigint,
  'createdBy' : string,
  'description' : string,
  'category' : string,
  'amount' : bigint,
}
export interface AdminNotification {
  'id' : string,
  'notificationType' : string,
  'createdAt' : bigint,
  'read' : boolean,
  'message' : string,
}
export interface AdminStats {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'totalRevenue' : bigint,
}
export interface AdminTask {
  'id' : string,
  'title' : string,
  'assignedTo' : [] | [string],
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'description' : string,
  'notes' : string,
  'category' : string,
  'priority' : string,
}
export interface B2BInquiry {
  'id' : bigint,
  'contactName' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'productInterest' : string,
  'companyName' : string,
  'quantity' : string,
  'phone' : string,
}
export interface B2BInquiryInput {
  'contactName' : string,
  'email' : string,
  'message' : string,
  'productInterest' : string,
  'companyName' : string,
  'quantity' : string,
  'phone' : string,
}
export interface BlogPost {
  'id' : string,
  'metaDescription' : string,
  'status' : string,
  'title' : string,
  'content' : string,
  'publishDate' : [] | [bigint],
  'featuredImage' : string,
  'createdAt' : bigint,
  'slug' : string,
  'tags' : Array<string>,
  'updatedAt' : bigint,
  'metaTitle' : string,
  'excerpt' : string,
}
export interface CartItem {
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export type Category = string;
export interface Coupon {
  'active' : boolean,
  'expiryDate' : bigint,
  'code' : string,
  'usedCount' : bigint,
  'discountPercent' : bigint,
  'maxUses' : bigint,
}
export interface CouponValidation {
  'valid' : boolean,
  'discountPercent' : bigint,
  'message' : string,
}
export interface CreateCouponInput {
  'expiryDate' : bigint,
  'code' : string,
  'discountPercent' : bigint,
  'maxUses' : bigint,
}
export interface CreateFlashSaleInput {
  'startTime' : bigint,
  'endTime' : bigint,
  'discountPercent' : bigint,
  'productId' : bigint,
}
export interface CreateOrderInput {
  'couponCode' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'address' : Address,
  'stripePaymentId' : [] | [string],
  'items' : Array<CartItem>,
}
export interface CreateProductInput {
  'featured' : boolean,
  'bundleIds' : Array<bigint>,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageKey' : string,
  'imageUrl' : string,
  'discount' : bigint,
  'category' : Category,
  'price' : bigint,
}
export interface FlashSale {
  'id' : bigint,
  'startTime' : bigint,
  'active' : boolean,
  'endTime' : bigint,
  'discountPercent' : bigint,
  'productId' : bigint,
}
export interface InventoryItem {
  'supplierContact' : string,
  'lowStockThreshold' : bigint,
  'purchaseCost' : bigint,
  'expiryDate' : [] | [bigint],
  'supplierName' : string,
  'lastUpdated' : bigint,
  'productId' : string,
  'incomingStock' : bigint,
  'reservedStock' : bigint,
  'batchNumber' : string,
  'currentStock' : bigint,
  'damagedStock' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'couponCode' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'userId' : Principal,
  'discountAmount' : bigint,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'address' : Address,
  'stripePaymentId' : [] | [string],
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export type PaymentMethod = { 'cod' : null } |
  { 'stripe' : null };
export interface Product {
  'id' : bigint,
  'featured' : boolean,
  'bundleIds' : Array<bigint>,
  'name' : string,
  'ratings' : number,
  'description' : string,
  'stock' : bigint,
  'imageKey' : string,
  'imageUrl' : string,
  'discount' : bigint,
  'category' : Category,
  'price' : bigint,
  'reviewCount' : bigint,
}
export interface ProductFilter {
  'featured' : [] | [boolean],
  'minRating' : [] | [number],
  'sortBy' : [] | [string],
  'maxPrice' : [] | [bigint],
  'category' : [] | [string],
  'minPrice' : [] | [bigint],
  'searchQuery' : [] | [string],
}
export interface Review {
  'id' : bigint,
  'verified' : boolean,
  'userId' : Principal,
  'createdAt' : bigint,
  'text' : string,
  'productId' : bigint,
  'approved' : boolean,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StoreSettings {
  'timezone' : string,
  'gstNumber' : string,
  'freeShippingThreshold' : bigint,
  'instagramUrl' : string,
  'whatsappNumber' : string,
  'currency' : string,
  'storeName' : string,
  'contactEmail' : string,
  'facebookUrl' : string,
  'contactPhone' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TeamMember {
  'id' : string,
  'permissions' : Array<string>,
  'active' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'email' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addExpense' : ActorMethod<[AdminExpense], AdminExpense>,
  'addReview' : ActorMethod<[AddReviewInput], Review>,
  'addTeamMember' : ActorMethod<[TeamMember], TeamMember>,
  'addToCart' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'approveReview' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllNotifications' : ActorMethod<[], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'completeAdminTask' : ActorMethod<[string], boolean>,
  'createAdminCoupon' : ActorMethod<[AdminCoupon], AdminCoupon>,
  'createAdminTask' : ActorMethod<[AdminTask], AdminTask>,
  'createBlogPost' : ActorMethod<[BlogPost], BlogPost>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCoupon' : ActorMethod<[CreateCouponInput], Coupon>,
  'createFlashSale' : ActorMethod<[CreateFlashSaleInput], FlashSale>,
  'createOrder' : ActorMethod<[CreateOrderInput], Order>,
  'createProduct' : ActorMethod<[CreateProductInput], Product>,
  'deleteAdminCoupon' : ActorMethod<[string], boolean>,
  'deleteAdminTask' : ActorMethod<[string], boolean>,
  'deleteBlogPost' : ActorMethod<[string], boolean>,
  'deleteExpense' : ActorMethod<[string], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'deleteReview' : ActorMethod<[bigint], boolean>,
  'deleteTeamMember' : ActorMethod<[string], boolean>,
  'endFlashSale' : ActorMethod<[bigint], boolean>,
  'getActiveFlashSales' : ActorMethod<[], Array<FlashSale>>,
  'getAdminCoupons' : ActorMethod<[], Array<AdminCoupon>>,
  'getAdminNotifications' : ActorMethod<[], Array<AdminNotification>>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAdminTasks' : ActorMethod<[], Array<AdminTask>>,
  'getAnalyticsSummary' : ActorMethod<
    [],
    {
      'totalOrders' : bigint,
      'totalExpenses' : bigint,
      'totalRevenue' : bigint,
      'totalCustomers' : bigint,
      'avgOrderValue' : bigint,
      'netProfit' : bigint,
    }
  >,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getExpenses' : ActorMethod<[], Array<AdminExpense>>,
  'getExpensesByCategory' : ActorMethod<[], Array<[string, bigint]>>,
  'getInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOutOfStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductReviews' : ActorMethod<[bigint], Array<Review>>,
  'getRecommendations' : ActorMethod<[string], Array<Product>>,
  'getStoreSettings' : ActorMethod<[], [] | [StoreSettings]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getWishlist' : ActorMethod<[], Array<bigint>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllOrders' : ActorMethod<[], Array<Order>>,
  'listB2BInquiries' : ActorMethod<[], Array<B2BInquiry>>,
  'listBundles' : ActorMethod<[], Array<Product>>,
  'listCoupons' : ActorMethod<[], Array<Coupon>>,
  'listEmails' : ActorMethod<[], Array<string>>,
  'listFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'listProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'listUserOrders' : ActorMethod<[], Array<Order>>,
  'markNotificationRead' : ActorMethod<[string], boolean>,
  'publishBlogPost' : ActorMethod<[string], boolean>,
  'redeemCoupon' : ActorMethod<[string], boolean>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'saveStoreSettings' : ActorMethod<[StoreSettings], StoreSettings>,
  'seedProducts' : ActorMethod<[], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'submitB2BInquiry' : ActorMethod<[B2BInquiryInput], B2BInquiry>,
  'subscribeEmail' : ActorMethod<[string], boolean>,
  'toggleCouponActive' : ActorMethod<[string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminCoupon' : ActorMethod<[string, AdminCoupon], [] | [AdminCoupon]>,
  'updateAdminTask' : ActorMethod<[string, AdminTask], [] | [AdminTask]>,
  'updateBlogPost' : ActorMethod<[string, BlogPost], [] | [BlogPost]>,
  'updateCartQuantity' : ActorMethod<[bigint, bigint], undefined>,
  'updateExpense' : ActorMethod<[string, AdminExpense], [] | [AdminExpense]>,
  'updateInventoryStock' : ActorMethod<
    [string, bigint, string],
    [] | [InventoryItem]
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], boolean>,
  'updateProduct' : ActorMethod<[bigint, CreateProductInput], boolean>,
  'updateTeamMember' : ActorMethod<[string, TeamMember], [] | [TeamMember]>,
  'upsertInventoryItem' : ActorMethod<[InventoryItem], InventoryItem>,
  'validateCoupon' : ActorMethod<[string], CouponValidation>,
  'verifyAdminCredentials' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];