/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminExpense = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Int,
  'createdBy' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const AddReviewInput = IDL.Record({
  'text' : IDL.Text,
  'productId' : IDL.Nat,
  'rating' : IDL.Nat,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'verified' : IDL.Bool,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'productId' : IDL.Nat,
  'approved' : IDL.Bool,
  'rating' : IDL.Nat,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Text,
  'permissions' : IDL.Vec(IDL.Text),
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminCoupon = IDL.Record({
  'id' : IDL.Text,
  'minCartValue' : IDL.Nat,
  'active' : IDL.Bool,
  'discountValue' : IDL.Nat,
  'expiresAt' : IDL.Opt(IDL.Int),
  'code' : IDL.Text,
  'createdAt' : IDL.Int,
  'discountType' : IDL.Text,
  'usedCount' : IDL.Nat,
  'description' : IDL.Text,
  'maxUses' : IDL.Nat,
});
export const AdminTask = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'priority' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'metaDescription' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Opt(IDL.Int),
  'featuredImage' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
  'metaTitle' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CreateCouponInput = IDL.Record({
  'expiryDate' : IDL.Int,
  'code' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'maxUses' : IDL.Nat,
});
export const Coupon = IDL.Record({
  'active' : IDL.Bool,
  'expiryDate' : IDL.Int,
  'code' : IDL.Text,
  'usedCount' : IDL.Nat,
  'discountPercent' : IDL.Nat,
  'maxUses' : IDL.Nat,
});
export const CreateFlashSaleInput = IDL.Record({
  'startTime' : IDL.Int,
  'endTime' : IDL.Int,
  'discountPercent' : IDL.Nat,
  'productId' : IDL.Nat,
});
export const FlashSale = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'active' : IDL.Bool,
  'endTime' : IDL.Int,
  'discountPercent' : IDL.Nat,
  'productId' : IDL.Nat,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'stripe' : IDL.Null,
});
export const Address__1 = IDL.Record({
  'country' : IDL.Text,
  'gstNumber' : IDL.Opt(IDL.Text),
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Opt(IDL.Text),
  'state' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const CreateOrderInput = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'paymentMethod' : PaymentMethod,
  'address' : Address__1,
  'stripePaymentId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(CartItem),
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'couponCode' : IDL.Opt(IDL.Text),
  'paymentMethod' : PaymentMethod,
  'userId' : IDL.Principal,
  'discountAmount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'address' : Address__1,
  'stripePaymentId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(CartItem),
});
export const Category = IDL.Text;
export const CreateProductInput = IDL.Record({
  'featured' : IDL.Bool,
  'bundleIds' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageKey' : IDL.Text,
  'imageUrl' : IDL.Text,
  'discount' : IDL.Nat,
  'category' : Category,
  'price' : IDL.Nat,
  'bestseller' : IDL.Bool,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'featured' : IDL.Bool,
  'bundleIds' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'ratings' : IDL.Float64,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageKey' : IDL.Text,
  'imageUrl' : IDL.Text,
  'discount' : IDL.Nat,
  'category' : Category,
  'price' : IDL.Nat,
  'bestseller' : IDL.Bool,
  'reviewCount' : IDL.Nat,
});
export const AdminNotification = IDL.Record({
  'id' : IDL.Text,
  'notificationType' : IDL.Text,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const AdminStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const ActivityType = IDL.Variant({
  'Login' : IDL.Null,
  'WishlistRemove' : IDL.Null,
  'CouponUsed' : IDL.Null,
  'OrderPlaced' : IDL.Null,
  'ProductView' : IDL.Null,
  'Logout' : IDL.Null,
  'NewsletterSignup' : IDL.Null,
  'ProfileUpdated' : IDL.Null,
  'CartAdd' : IDL.Null,
  'SearchQuery' : IDL.Null,
  'ReviewSubmitted' : IDL.Null,
  'WishlistAdd' : IDL.Null,
  'B2BInquiry' : IDL.Null,
  'CartRemove' : IDL.Null,
  'AddressAdded' : IDL.Null,
});
export const UserActivity = IDL.Record({
  'id' : IDL.Nat,
  'activityType' : ActivityType,
  'metadata' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Address = IDL.Record({
  'tag' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'state' : IDL.Text,
  'isDefault' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'addresses' : IDL.Vec(Address),
  'phone' : IDL.Text,
});
export const EnrichedCustomerProfile = IDL.Record({
  'id' : IDL.Principal,
  'status' : IDL.Text,
  'totalOrders' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'totalSpend' : IDL.Nat,
  'phone' : IDL.Text,
  'lastLogin' : IDL.Opt(IDL.Int),
  'activityCount' : IDL.Nat,
});
export const B2BInquiry = IDL.Record({
  'id' : IDL.Nat,
  'contactName' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'productInterest' : IDL.Text,
  'companyName' : IDL.Text,
  'quantity' : IDL.Text,
  'phone' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'supplierContact' : IDL.Text,
  'lowStockThreshold' : IDL.Nat,
  'purchaseCost' : IDL.Nat,
  'expiryDate' : IDL.Opt(IDL.Int),
  'supplierName' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'productId' : IDL.Text,
  'incomingStock' : IDL.Nat,
  'reservedStock' : IDL.Nat,
  'batchNumber' : IDL.Text,
  'currentStock' : IDL.Nat,
  'damagedStock' : IDL.Nat,
});
export const ProductFilter = IDL.Record({
  'featured' : IDL.Opt(IDL.Bool),
  'minRating' : IDL.Opt(IDL.Float64),
  'sortBy' : IDL.Opt(IDL.Text),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'category' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
  'searchQuery' : IDL.Opt(IDL.Text),
});
export const StoreSettings = IDL.Record({
  'timezone' : IDL.Text,
  'gstNumber' : IDL.Text,
  'freeShippingThreshold' : IDL.Nat,
  'instagramUrl' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'currency' : IDL.Text,
  'storeName' : IDL.Text,
  'contactEmail' : IDL.Text,
  'facebookUrl' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const RegisterUserInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const B2BInquiryInput = IDL.Record({
  'contactName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'productInterest' : IDL.Text,
  'companyName' : IDL.Text,
  'quantity' : IDL.Text,
  'phone' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateUserInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'addresses' : IDL.Vec(Address),
  'phone' : IDL.Text,
});
export const CouponValidation = IDL.Record({
  'valid' : IDL.Bool,
  'discountPercent' : IDL.Nat,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addExpense' : IDL.Func([AdminExpense], [AdminExpense], []),
  'addReview' : IDL.Func([AddReviewInput], [Review], []),
  'addTeamMember' : IDL.Func([TeamMember], [TeamMember], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'approveReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'clearAllNotifications' : IDL.Func([], [], []),
  'clearCart' : IDL.Func([], [], []),
  'completeAdminTask' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createAdminCoupon' : IDL.Func([AdminCoupon], [AdminCoupon], []),
  'createAdminTask' : IDL.Func([AdminTask], [AdminTask], []),
  'createBlogPost' : IDL.Func([BlogPost], [BlogPost], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCoupon' : IDL.Func([CreateCouponInput], [Coupon], []),
  'createFlashSale' : IDL.Func([CreateFlashSaleInput], [FlashSale], []),
  'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
  'createProduct' : IDL.Func([CreateProductInput], [Product], []),
  'createReview' : IDL.Func([AddReviewInput], [Review], []),
  'createTask' : IDL.Func([AdminTask], [AdminTask], []),
  'deactivateFlashSale' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteAdminCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteAdminTask' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteExpense' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTask' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTeamMember' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'endFlashSale' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getActiveFlashSales' : IDL.Func([], [IDL.Vec(FlashSale)], ['query']),
  'getAdminCoupons' : IDL.Func([], [IDL.Vec(AdminCoupon)], ['query']),
  'getAdminNotifications' : IDL.Func(
      [],
      [IDL.Vec(AdminNotification)],
      ['query'],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAdminTasks' : IDL.Func([], [IDL.Vec(AdminTask)], ['query']),
  'getAllActivities' : IDL.Func([], [IDL.Vec(UserActivity)], ['query']),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllCustomersEnriched' : IDL.Func(
      [],
      [IDL.Vec(EnrichedCustomerProfile)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalOrders' : IDL.Nat,
          'totalActivities' : IDL.Nat,
          'newUsersToday' : IDL.Nat,
          'recentActivities' : IDL.Vec(UserActivity),
          'activeUsersToday' : IDL.Nat,
          'totalRegisteredUsers' : IDL.Nat,
          'totalExpenses' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
          'totalCustomers' : IDL.Nat,
          'avgOrderValue' : IDL.Nat,
          'netProfit' : IDL.Int,
        }),
      ],
      ['query'],
    ),
  'getB2BInquiries' : IDL.Func([], [IDL.Vec(B2BInquiry)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getCustomerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(EnrichedCustomerProfile)],
      ['query'],
    ),
  'getExpenses' : IDL.Func([], [IDL.Vec(AdminExpense)], ['query']),
  'getExpensesByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getNewsletterSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'getRecommendations' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getStoreSettings' : IDL.Func([], [IDL.Opt(StoreSettings)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTasks' : IDL.Func([], [IDL.Vec(AdminTask)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getUserActivities' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [IDL.Vec(UserActivity)],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isWishlisted' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listB2BInquiries' : IDL.Func([], [IDL.Vec(B2BInquiry)], ['query']),
  'listBundles' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'listUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'logUserActivity' : IDL.Func([ActivityType, IDL.Text], [UserActivity], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'placeOrder' : IDL.Func([CreateOrderInput], [Order], []),
  'publishBlogPost' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'redeemCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'registerUser' : IDL.Func([RegisterUserInput], [UserProfile], []),
  'rejectReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  'removeTeamMember' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveStoreSettings' : IDL.Func([StoreSettings], [StoreSettings], []),
  'seedProducts' : IDL.Func([], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'submitB2BInquiry' : IDL.Func([B2BInquiryInput], [B2BInquiry], []),
  'subscribeEmail' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'toggleBestseller' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleCouponActive' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'toggleFeatured' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdminCoupon' : IDL.Func(
      [IDL.Text, AdminCoupon],
      [IDL.Opt(AdminCoupon)],
      [],
    ),
  'updateAdminTask' : IDL.Func([IDL.Text, AdminTask], [IDL.Opt(AdminTask)], []),
  'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [IDL.Opt(BlogPost)], []),
  'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateExpense' : IDL.Func(
      [IDL.Text, AdminExpense],
      [IDL.Opt(AdminExpense)],
      [],
    ),
  'updateInventory' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text, IDL.Text],
      [IDL.Opt(InventoryItem)],
      [],
    ),
  'updateInventoryStock' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text],
      [IDL.Opt(InventoryItem)],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
  'updateProduct' : IDL.Func([IDL.Nat, CreateProductInput], [IDL.Bool], []),
  'updateStoreSettings' : IDL.Func([StoreSettings], [StoreSettings], []),
  'updateTask' : IDL.Func([IDL.Text, AdminTask], [IDL.Opt(AdminTask)], []),
  'updateTeamMember' : IDL.Func(
      [IDL.Text, TeamMember],
      [IDL.Opt(TeamMember)],
      [],
    ),
  'updateUserProfile' : IDL.Func([UpdateUserInput], [IDL.Opt(UserProfile)], []),
  'upsertInventoryItem' : IDL.Func([InventoryItem], [InventoryItem], []),
  'validateCoupon' : IDL.Func([IDL.Text], [CouponValidation], ['query']),
  'verifyAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminExpense = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Int,
    'createdBy' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const AddReviewInput = IDL.Record({
    'text' : IDL.Text,
    'productId' : IDL.Nat,
    'rating' : IDL.Nat,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'verified' : IDL.Bool,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'productId' : IDL.Nat,
    'approved' : IDL.Bool,
    'rating' : IDL.Nat,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Text,
    'permissions' : IDL.Vec(IDL.Text),
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminCoupon = IDL.Record({
    'id' : IDL.Text,
    'minCartValue' : IDL.Nat,
    'active' : IDL.Bool,
    'discountValue' : IDL.Nat,
    'expiresAt' : IDL.Opt(IDL.Int),
    'code' : IDL.Text,
    'createdAt' : IDL.Int,
    'discountType' : IDL.Text,
    'usedCount' : IDL.Nat,
    'description' : IDL.Text,
    'maxUses' : IDL.Nat,
  });
  const AdminTask = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'priority' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'metaDescription' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Opt(IDL.Int),
    'featuredImage' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
    'metaTitle' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CreateCouponInput = IDL.Record({
    'expiryDate' : IDL.Int,
    'code' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'maxUses' : IDL.Nat,
  });
  const Coupon = IDL.Record({
    'active' : IDL.Bool,
    'expiryDate' : IDL.Int,
    'code' : IDL.Text,
    'usedCount' : IDL.Nat,
    'discountPercent' : IDL.Nat,
    'maxUses' : IDL.Nat,
  });
  const CreateFlashSaleInput = IDL.Record({
    'startTime' : IDL.Int,
    'endTime' : IDL.Int,
    'discountPercent' : IDL.Nat,
    'productId' : IDL.Nat,
  });
  const FlashSale = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'active' : IDL.Bool,
    'endTime' : IDL.Int,
    'discountPercent' : IDL.Nat,
    'productId' : IDL.Nat,
  });
  const PaymentMethod = IDL.Variant({ 'cod' : IDL.Null, 'stripe' : IDL.Null });
  const Address__1 = IDL.Record({
    'country' : IDL.Text,
    'gstNumber' : IDL.Opt(IDL.Text),
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Opt(IDL.Text),
    'state' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const CreateOrderInput = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'paymentMethod' : PaymentMethod,
    'address' : Address__1,
    'stripePaymentId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(CartItem),
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'couponCode' : IDL.Opt(IDL.Text),
    'paymentMethod' : PaymentMethod,
    'userId' : IDL.Principal,
    'discountAmount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'address' : Address__1,
    'stripePaymentId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(CartItem),
  });
  const Category = IDL.Text;
  const CreateProductInput = IDL.Record({
    'featured' : IDL.Bool,
    'bundleIds' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageKey' : IDL.Text,
    'imageUrl' : IDL.Text,
    'discount' : IDL.Nat,
    'category' : Category,
    'price' : IDL.Nat,
    'bestseller' : IDL.Bool,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'featured' : IDL.Bool,
    'bundleIds' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'ratings' : IDL.Float64,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageKey' : IDL.Text,
    'imageUrl' : IDL.Text,
    'discount' : IDL.Nat,
    'category' : Category,
    'price' : IDL.Nat,
    'bestseller' : IDL.Bool,
    'reviewCount' : IDL.Nat,
  });
  const AdminNotification = IDL.Record({
    'id' : IDL.Text,
    'notificationType' : IDL.Text,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const AdminStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const ActivityType = IDL.Variant({
    'Login' : IDL.Null,
    'WishlistRemove' : IDL.Null,
    'CouponUsed' : IDL.Null,
    'OrderPlaced' : IDL.Null,
    'ProductView' : IDL.Null,
    'Logout' : IDL.Null,
    'NewsletterSignup' : IDL.Null,
    'ProfileUpdated' : IDL.Null,
    'CartAdd' : IDL.Null,
    'SearchQuery' : IDL.Null,
    'ReviewSubmitted' : IDL.Null,
    'WishlistAdd' : IDL.Null,
    'B2BInquiry' : IDL.Null,
    'CartRemove' : IDL.Null,
    'AddressAdded' : IDL.Null,
  });
  const UserActivity = IDL.Record({
    'id' : IDL.Nat,
    'activityType' : ActivityType,
    'metadata' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Address = IDL.Record({
    'tag' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'state' : IDL.Text,
    'isDefault' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'addresses' : IDL.Vec(Address),
    'phone' : IDL.Text,
  });
  const EnrichedCustomerProfile = IDL.Record({
    'id' : IDL.Principal,
    'status' : IDL.Text,
    'totalOrders' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'totalSpend' : IDL.Nat,
    'phone' : IDL.Text,
    'lastLogin' : IDL.Opt(IDL.Int),
    'activityCount' : IDL.Nat,
  });
  const B2BInquiry = IDL.Record({
    'id' : IDL.Nat,
    'contactName' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'productInterest' : IDL.Text,
    'companyName' : IDL.Text,
    'quantity' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'supplierContact' : IDL.Text,
    'lowStockThreshold' : IDL.Nat,
    'purchaseCost' : IDL.Nat,
    'expiryDate' : IDL.Opt(IDL.Int),
    'supplierName' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'productId' : IDL.Text,
    'incomingStock' : IDL.Nat,
    'reservedStock' : IDL.Nat,
    'batchNumber' : IDL.Text,
    'currentStock' : IDL.Nat,
    'damagedStock' : IDL.Nat,
  });
  const ProductFilter = IDL.Record({
    'featured' : IDL.Opt(IDL.Bool),
    'minRating' : IDL.Opt(IDL.Float64),
    'sortBy' : IDL.Opt(IDL.Text),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'category' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  const StoreSettings = IDL.Record({
    'timezone' : IDL.Text,
    'gstNumber' : IDL.Text,
    'freeShippingThreshold' : IDL.Nat,
    'instagramUrl' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'currency' : IDL.Text,
    'storeName' : IDL.Text,
    'contactEmail' : IDL.Text,
    'facebookUrl' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const RegisterUserInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const B2BInquiryInput = IDL.Record({
    'contactName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'productInterest' : IDL.Text,
    'companyName' : IDL.Text,
    'quantity' : IDL.Text,
    'phone' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateUserInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'addresses' : IDL.Vec(Address),
    'phone' : IDL.Text,
  });
  const CouponValidation = IDL.Record({
    'valid' : IDL.Bool,
    'discountPercent' : IDL.Nat,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addExpense' : IDL.Func([AdminExpense], [AdminExpense], []),
    'addReview' : IDL.Func([AddReviewInput], [Review], []),
    'addTeamMember' : IDL.Func([TeamMember], [TeamMember], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'approveReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'clearAllNotifications' : IDL.Func([], [], []),
    'clearCart' : IDL.Func([], [], []),
    'completeAdminTask' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createAdminCoupon' : IDL.Func([AdminCoupon], [AdminCoupon], []),
    'createAdminTask' : IDL.Func([AdminTask], [AdminTask], []),
    'createBlogPost' : IDL.Func([BlogPost], [BlogPost], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCoupon' : IDL.Func([CreateCouponInput], [Coupon], []),
    'createFlashSale' : IDL.Func([CreateFlashSaleInput], [FlashSale], []),
    'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
    'createProduct' : IDL.Func([CreateProductInput], [Product], []),
    'createReview' : IDL.Func([AddReviewInput], [Review], []),
    'createTask' : IDL.Func([AdminTask], [AdminTask], []),
    'deactivateFlashSale' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteAdminCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteAdminTask' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteExpense' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTask' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTeamMember' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'endFlashSale' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getActiveFlashSales' : IDL.Func([], [IDL.Vec(FlashSale)], ['query']),
    'getAdminCoupons' : IDL.Func([], [IDL.Vec(AdminCoupon)], ['query']),
    'getAdminNotifications' : IDL.Func(
        [],
        [IDL.Vec(AdminNotification)],
        ['query'],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAdminTasks' : IDL.Func([], [IDL.Vec(AdminTask)], ['query']),
    'getAllActivities' : IDL.Func([], [IDL.Vec(UserActivity)], ['query']),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllCustomersEnriched' : IDL.Func(
        [],
        [IDL.Vec(EnrichedCustomerProfile)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalOrders' : IDL.Nat,
            'totalActivities' : IDL.Nat,
            'newUsersToday' : IDL.Nat,
            'recentActivities' : IDL.Vec(UserActivity),
            'activeUsersToday' : IDL.Nat,
            'totalRegisteredUsers' : IDL.Nat,
            'totalExpenses' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
            'totalCustomers' : IDL.Nat,
            'avgOrderValue' : IDL.Nat,
            'netProfit' : IDL.Int,
          }),
        ],
        ['query'],
      ),
    'getB2BInquiries' : IDL.Func([], [IDL.Vec(B2BInquiry)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getCustomerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(EnrichedCustomerProfile)],
        ['query'],
      ),
    'getExpenses' : IDL.Func([], [IDL.Vec(AdminExpense)], ['query']),
    'getExpensesByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getNewsletterSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'getRecommendations' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getStoreSettings' : IDL.Func([], [IDL.Opt(StoreSettings)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTasks' : IDL.Func([], [IDL.Vec(AdminTask)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getUserActivities' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [IDL.Vec(UserActivity)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isWishlisted' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listB2BInquiries' : IDL.Func([], [IDL.Vec(B2BInquiry)], ['query']),
    'listBundles' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'listUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'logUserActivity' : IDL.Func([ActivityType, IDL.Text], [UserActivity], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'placeOrder' : IDL.Func([CreateOrderInput], [Order], []),
    'publishBlogPost' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'redeemCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'registerUser' : IDL.Func([RegisterUserInput], [UserProfile], []),
    'rejectReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
    'removeTeamMember' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveStoreSettings' : IDL.Func([StoreSettings], [StoreSettings], []),
    'seedProducts' : IDL.Func([], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'submitB2BInquiry' : IDL.Func([B2BInquiryInput], [B2BInquiry], []),
    'subscribeEmail' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'toggleBestseller' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleCouponActive' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'toggleFeatured' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdminCoupon' : IDL.Func(
        [IDL.Text, AdminCoupon],
        [IDL.Opt(AdminCoupon)],
        [],
      ),
    'updateAdminTask' : IDL.Func(
        [IDL.Text, AdminTask],
        [IDL.Opt(AdminTask)],
        [],
      ),
    'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [IDL.Opt(BlogPost)], []),
    'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateExpense' : IDL.Func(
        [IDL.Text, AdminExpense],
        [IDL.Opt(AdminExpense)],
        [],
      ),
    'updateInventory' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text, IDL.Text],
        [IDL.Opt(InventoryItem)],
        [],
      ),
    'updateInventoryStock' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text],
        [IDL.Opt(InventoryItem)],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
    'updateProduct' : IDL.Func([IDL.Nat, CreateProductInput], [IDL.Bool], []),
    'updateStoreSettings' : IDL.Func([StoreSettings], [StoreSettings], []),
    'updateTask' : IDL.Func([IDL.Text, AdminTask], [IDL.Opt(AdminTask)], []),
    'updateTeamMember' : IDL.Func(
        [IDL.Text, TeamMember],
        [IDL.Opt(TeamMember)],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [UpdateUserInput],
        [IDL.Opt(UserProfile)],
        [],
      ),
    'upsertInventoryItem' : IDL.Func([InventoryItem], [InventoryItem], []),
    'validateCoupon' : IDL.Func([IDL.Text], [CouponValidation], ['query']),
    'verifyAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };