/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdminTask {
    id: string;
    title: string;
    assignedTo?: string;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    notes: string;
    category: string;
    priority: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AdminExpense {
    id: string;
    date: bigint;
    createdBy: string;
    description: string;
    category: string;
    amount: bigint;
}
export interface AddReviewInput {
    text: string;
    productId: bigint;
    rating: bigint;
}
export interface StoreSettings {
    timezone: string;
    gstNumber: string;
    freeShippingThreshold: bigint;
    instagramUrl: string;
    whatsappNumber: string;
    currency: string;
    storeName: string;
    contactEmail: string;
    facebookUrl: string;
    contactPhone: string;
}
export interface B2BInquiry {
    id: bigint;
    contactName: string;
    createdAt: bigint;
    email: string;
    message: string;
    productInterest: string;
    companyName: string;
    quantity: string;
    phone: string;
}
export interface InventoryItem {
    supplierContact: string;
    lowStockThreshold: bigint;
    purchaseCost: bigint;
    expiryDate?: bigint;
    supplierName: string;
    lastUpdated: bigint;
    productId: string;
    incomingStock: bigint;
    reservedStock: bigint;
    batchNumber: string;
    currentStock: bigint;
    damagedStock: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface CouponValidation {
    valid: boolean;
    discountPercent: bigint;
    message: string;
}
export interface CreateOrderInput {
    couponCode?: string;
    paymentMethod: PaymentMethod;
    address: Address;
    stripePaymentId?: string;
    items: Array<CartItem>;
}
export interface B2BInquiryInput {
    contactName: string;
    email: string;
    message: string;
    productInterest: string;
    companyName: string;
    quantity: string;
    phone: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type Category = string;
export interface Review {
    id: bigint;
    verified: boolean;
    userId: Principal;
    createdAt: bigint;
    text: string;
    productId: bigint;
    approved: boolean;
    rating: bigint;
}
export interface BlogPost {
    id: string;
    metaDescription: string;
    status: string;
    title: string;
    content: string;
    publishDate?: bigint;
    featuredImage: string;
    createdAt: bigint;
    slug: string;
    tags: Array<string>;
    updatedAt: bigint;
    metaTitle: string;
    excerpt: string;
}
export interface Coupon {
    active: boolean;
    expiryDate: bigint;
    code: string;
    usedCount: bigint;
    discountPercent: bigint;
    maxUses: bigint;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    couponCode?: string;
    paymentMethod: PaymentMethod;
    userId: Principal;
    discountAmount: bigint;
    createdAt: bigint;
    totalAmount: bigint;
    address: Address;
    stripePaymentId?: string;
    items: Array<CartItem>;
}
export interface ProductFilter {
    featured?: boolean;
    minRating?: number;
    sortBy?: string;
    maxPrice?: bigint;
    category?: string;
    minPrice?: bigint;
    searchQuery?: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CreateProductInput {
    featured: boolean;
    bundleIds: Array<bigint>;
    name: string;
    description: string;
    stock: bigint;
    imageKey: string;
    imageUrl: string;
    discount: bigint;
    category: Category;
    price: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface AdminStats {
    totalProducts: bigint;
    totalOrders: bigint;
    totalRevenue: bigint;
}
export interface AdminNotification {
    id: string;
    notificationType: string;
    createdAt: bigint;
    read: boolean;
    message: string;
}
export interface CreateFlashSaleInput {
    startTime: bigint;
    endTime: bigint;
    discountPercent: bigint;
    productId: bigint;
}
export interface CreateCouponInput {
    expiryDate: bigint;
    code: string;
    discountPercent: bigint;
    maxUses: bigint;
}
export interface AdminCoupon {
    id: string;
    minCartValue: bigint;
    active: boolean;
    discountValue: bigint;
    expiresAt?: bigint;
    code: string;
    createdAt: bigint;
    discountType: string;
    usedCount: bigint;
    description: string;
    maxUses: bigint;
}
export interface TeamMember {
    id: string;
    permissions: Array<string>;
    active: boolean;
    name: string;
    createdAt: bigint;
    role: string;
    email: string;
}
export interface CartItem {
    productId: bigint;
    quantity: bigint;
    price: bigint;
}
export interface FlashSale {
    id: bigint;
    startTime: bigint;
    active: boolean;
    endTime: bigint;
    discountPercent: bigint;
    productId: bigint;
}
export interface Product {
    id: bigint;
    featured: boolean;
    bundleIds: Array<bigint>;
    name: string;
    ratings: number;
    description: string;
    stock: bigint;
    imageKey: string;
    imageUrl: string;
    discount: bigint;
    category: Category;
    price: bigint;
    reviewCount: bigint;
}
export interface Address {
    street: string;
    country: string;
    gstNumber?: string;
    city: string;
    postalCode: string;
    state: string;
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    delivered = "delivered",
    processing = "processing"
}
export enum PaymentMethod {
    cod = "cod",
    stripe = "stripe"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addExpense(expense: AdminExpense): Promise<AdminExpense>;
    addReview(input: AddReviewInput): Promise<Review>;
    addTeamMember(member: TeamMember): Promise<TeamMember>;
    addToCart(productId: bigint, quantity: bigint, price: bigint): Promise<void>;
    addToWishlist(productId: bigint): Promise<void>;
    approveReview(reviewId: bigint): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearAllNotifications(): Promise<void>;
    clearCart(): Promise<void>;
    completeAdminTask(id: string): Promise<boolean>;
    createAdminCoupon(coupon: AdminCoupon): Promise<AdminCoupon>;
    createAdminTask(task: AdminTask): Promise<AdminTask>;
    createBlogPost(post: BlogPost): Promise<BlogPost>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createCoupon(input: CreateCouponInput): Promise<Coupon>;
    createFlashSale(input: CreateFlashSaleInput): Promise<FlashSale>;
    createOrder(input: CreateOrderInput): Promise<Order>;
    createProduct(input: CreateProductInput): Promise<Product>;
    deleteAdminCoupon(id: string): Promise<boolean>;
    deleteAdminTask(id: string): Promise<boolean>;
    deleteBlogPost(id: string): Promise<boolean>;
    deleteExpense(id: string): Promise<boolean>;
    deleteProduct(id: bigint): Promise<boolean>;
    deleteReview(reviewId: bigint): Promise<boolean>;
    deleteTeamMember(id: string): Promise<boolean>;
    endFlashSale(id: bigint): Promise<boolean>;
    getActiveFlashSales(): Promise<Array<FlashSale>>;
    getAdminCoupons(): Promise<Array<AdminCoupon>>;
    getAdminNotifications(): Promise<Array<AdminNotification>>;
    getAdminStats(): Promise<AdminStats>;
    getAdminTasks(): Promise<Array<AdminTask>>;
    getAnalyticsSummary(): Promise<{
        totalOrders: bigint;
        totalExpenses: bigint;
        totalRevenue: bigint;
        totalCustomers: bigint;
        avgOrderValue: bigint;
        netProfit: bigint;
    }>;
    getBlogPosts(): Promise<Array<BlogPost>>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Array<CartItem>>;
    getExpenses(): Promise<Array<AdminExpense>>;
    getExpensesByCategory(): Promise<Array<[string, bigint]>>;
    getInventoryItems(): Promise<Array<InventoryItem>>;
    getLowStockItems(): Promise<Array<InventoryItem>>;
    getOrder(id: bigint): Promise<Order | null>;
    getOutOfStockItems(): Promise<Array<InventoryItem>>;
    getProduct(id: bigint): Promise<Product | null>;
    getProductReviews(productId: bigint): Promise<Array<Review>>;
    getRecommendations(condition: string): Promise<Array<Product>>;
    getStoreSettings(): Promise<StoreSettings | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTeamMembers(): Promise<Array<TeamMember>>;
    getWishlist(): Promise<Array<bigint>>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAllOrders(): Promise<Array<Order>>;
    listB2BInquiries(): Promise<Array<B2BInquiry>>;
    listBundles(): Promise<Array<Product>>;
    listCoupons(): Promise<Array<Coupon>>;
    listEmails(): Promise<Array<string>>;
    listFeaturedProducts(): Promise<Array<Product>>;
    listProducts(filter: ProductFilter): Promise<Array<Product>>;
    listUserOrders(): Promise<Array<Order>>;
    markNotificationRead(id: string): Promise<boolean>;
    publishBlogPost(id: string): Promise<boolean>;
    redeemCoupon(code: string): Promise<boolean>;
    removeFromCart(productId: bigint): Promise<void>;
    removeFromWishlist(productId: bigint): Promise<void>;
    saveStoreSettings(settings: StoreSettings): Promise<StoreSettings>;
    seedProducts(): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setUserRole(user: Principal, role: UserRole): Promise<void>;
    submitB2BInquiry(input: B2BInquiryInput): Promise<B2BInquiry>;
    subscribeEmail(email: string): Promise<boolean>;
    toggleCouponActive(id: string): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAdminCoupon(id: string, coupon: AdminCoupon): Promise<AdminCoupon | null>;
    updateAdminTask(id: string, task: AdminTask): Promise<AdminTask | null>;
    updateBlogPost(id: string, post: BlogPost): Promise<BlogPost | null>;
    updateCartQuantity(productId: bigint, quantity: bigint): Promise<void>;
    updateExpense(id: string, expense: AdminExpense): Promise<AdminExpense | null>;
    updateInventoryStock(productId: string, delta: bigint, _reason: string): Promise<InventoryItem | null>;
    updateOrderStatus(id: bigint, status: OrderStatus): Promise<boolean>;
    updateProduct(id: bigint, input: CreateProductInput): Promise<boolean>;
    updateTeamMember(id: string, member: TeamMember): Promise<TeamMember | null>;
    upsertInventoryItem(item: InventoryItem): Promise<InventoryItem>;
    validateCoupon(code: string): Promise<CouponValidation>;
    verifyAdminCredentials(username: string, password: string): Promise<boolean>;
}
import type { Address as _Address, AdminCoupon as _AdminCoupon, AdminExpense as _AdminExpense, AdminTask as _AdminTask, BlogPost as _BlogPost, CartItem as _CartItem, CreateOrderInput as _CreateOrderInput, InventoryItem as _InventoryItem, Order as _Order, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, Product as _Product, ProductFilter as _ProductFilter, StoreSettings as _StoreSettings, StripeSessionStatus as _StripeSessionStatus, TeamMember as _TeamMember, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addExpense(arg0: AdminExpense): Promise<AdminExpense> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0);
            return result;
        }
    }
    async addReview(arg0: AddReviewInput): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async addTeamMember(arg0: TeamMember): Promise<TeamMember> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeamMember(arg0);
            return result;
        }
    }
    async addToCart(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1, arg2);
            return result;
        }
    }
    async addToWishlist(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async approveReview(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReview(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearAllNotifications(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllNotifications();
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async completeAdminTask(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeAdminTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeAdminTask(arg0);
            return result;
        }
    }
    async createAdminCoupon(arg0: AdminCoupon): Promise<AdminCoupon> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdminCoupon(to_candid_AdminCoupon_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AdminCoupon_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdminCoupon(to_candid_AdminCoupon_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AdminCoupon_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAdminTask(arg0: AdminTask): Promise<AdminTask> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdminTask(to_candid_AdminTask_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AdminTask_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdminTask(to_candid_AdminTask_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AdminTask_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBlogPost(arg0: BlogPost): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(to_candid_BlogPost_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BlogPost_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(to_candid_BlogPost_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BlogPost_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createCoupon(arg0: CreateCouponInput): Promise<Coupon> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoupon(arg0);
            return result;
        }
    }
    async createFlashSale(arg0: CreateFlashSaleInput): Promise<FlashSale> {
        if (this.processError) {
            try {
                const result = await this.actor.createFlashSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFlashSale(arg0);
            return result;
        }
    }
    async createOrder(arg0: CreateOrderInput): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_CreateOrderInput_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_CreateOrderInput_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: CreateProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return result;
        }
    }
    async deleteAdminCoupon(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdminCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdminCoupon(arg0);
            return result;
        }
    }
    async deleteAdminTask(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdminTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdminTask(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteReview(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async deleteTeamMember(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeamMember(arg0);
            return result;
        }
    }
    async endFlashSale(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.endFlashSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endFlashSale(arg0);
            return result;
        }
    }
    async getActiveFlashSales(): Promise<Array<FlashSale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveFlashSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveFlashSales();
            return result;
        }
    }
    async getAdminCoupons(): Promise<Array<AdminCoupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminCoupons();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminCoupons();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminNotifications(): Promise<Array<AdminNotification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminNotifications();
            return result;
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAdminTasks(): Promise<Array<AdminTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminTasks();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminTasks();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsSummary(): Promise<{
        totalOrders: bigint;
        totalExpenses: bigint;
        totalRevenue: bigint;
        totalCustomers: bigint;
        avgOrderValue: bigint;
        netProfit: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary();
            return result;
        }
    }
    async getBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getExpenses(): Promise<Array<AdminExpense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return result;
        }
    }
    async getExpensesByCategory(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByCategory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByCategory();
            return result;
        }
    }
    async getInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItems();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItems();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockItems();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockItems();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOutOfStockItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutOfStockItems();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutOfStockItems();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductReviews(arg0);
            return result;
        }
    }
    async getRecommendations(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendations(arg0);
            return result;
        }
    }
    async getStoreSettings(): Promise<StoreSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreSettings();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreSettings();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMembers();
            return result;
        }
    }
    async getWishlist(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllOrders();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllOrders();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listB2BInquiries(): Promise<Array<B2BInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listB2BInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listB2BInquiries();
            return result;
        }
    }
    async listBundles(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBundles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBundles();
            return result;
        }
    }
    async listCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCoupons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCoupons();
            return result;
        }
    }
    async listEmails(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmails();
            return result;
        }
    }
    async listFeaturedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeaturedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeaturedProducts();
            return result;
        }
    }
    async listProducts(arg0: ProductFilter): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_ProductFilter_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_ProductFilter_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listUserOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserOrders();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserOrders();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationRead(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async publishBlogPost(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.publishBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishBlogPost(arg0);
            return result;
        }
    }
    async redeemCoupon(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemCoupon(arg0);
            return result;
        }
    }
    async removeFromCart(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async removeFromWishlist(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async saveStoreSettings(arg0: StoreSettings): Promise<StoreSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStoreSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStoreSettings(arg0);
            return result;
        }
    }
    async seedProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedProducts();
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitB2BInquiry(arg0: B2BInquiryInput): Promise<B2BInquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.submitB2BInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitB2BInquiry(arg0);
            return result;
        }
    }
    async subscribeEmail(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeEmail(arg0);
            return result;
        }
    }
    async toggleCouponActive(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCouponActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCouponActive(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAdminCoupon(arg0: string, arg1: AdminCoupon): Promise<AdminCoupon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminCoupon(arg0, to_candid_AdminCoupon_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminCoupon(arg0, to_candid_AdminCoupon_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAdminTask(arg0: string, arg1: AdminTask): Promise<AdminTask | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminTask(arg0, to_candid_AdminTask_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminTask(arg0, to_candid_AdminTask_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBlogPost(arg0: string, arg1: BlogPost): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, to_candid_BlogPost_n13(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, to_candid_BlogPost_n13(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCartQuantity(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartQuantity(arg0, arg1);
            return result;
        }
    }
    async updateExpense(arg0: string, arg1: AdminExpense): Promise<AdminExpense | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, arg1);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, arg1);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInventoryStock(arg0: string, arg1: bigint, arg2: string): Promise<InventoryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryStock(arg0, arg1, arg2);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryStock(arg0, arg1, arg2);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n53(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n53(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: CreateProductInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1);
            return result;
        }
    }
    async updateTeamMember(arg0: string, arg1: TeamMember): Promise<TeamMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamMember(arg0, arg1);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamMember(arg0, arg1);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertInventoryItem(arg0: InventoryItem): Promise<InventoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertInventoryItem(to_candid_InventoryItem_n56(this._uploadFile, this._downloadFile, arg0));
                return from_candid_InventoryItem_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertInventoryItem(to_candid_InventoryItem_n56(this._uploadFile, this._downloadFile, arg0));
            return from_candid_InventoryItem_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateCoupon(arg0: string): Promise<CouponValidation> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0);
            return result;
        }
    }
    async verifyAdminCredentials(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminCredentials(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Address_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Address): Address {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_AdminCoupon_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminCoupon): AdminCoupon {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_AdminTask_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminTask): AdminTask {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_BlogPost_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): BlogPost {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryItem_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StoreSettings]): StoreSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminCoupon]): AdminCoupon | null {
    return value.length === 0 ? null : from_candid_AdminCoupon_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminTask]): AdminTask | null {
    return value.length === 0 ? null : from_candid_AdminTask_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : from_candid_BlogPost_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminExpense]): AdminExpense | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventoryItem]): InventoryItem | null {
    return value.length === 0 ? null : from_candid_InventoryItem_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamMember]): TeamMember | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    assignedTo: [] | [string];
    createdAt: bigint;
    completed: boolean;
    dueDate: [] | [bigint];
    description: string;
    notes: string;
    category: string;
    priority: string;
}): {
    id: string;
    title: string;
    assignedTo?: string;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    notes: string;
    category: string;
    priority: string;
} {
    return {
        id: value.id,
        title: value.title,
        assignedTo: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.assignedTo)),
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        notes: value.notes,
        category: value.category,
        priority: value.priority
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    metaDescription: string;
    status: string;
    title: string;
    content: string;
    publishDate: [] | [bigint];
    featuredImage: string;
    createdAt: bigint;
    slug: string;
    tags: Array<string>;
    updatedAt: bigint;
    metaTitle: string;
    excerpt: string;
}): {
    id: string;
    metaDescription: string;
    status: string;
    title: string;
    content: string;
    publishDate?: bigint;
    featuredImage: string;
    createdAt: bigint;
    slug: string;
    tags: Array<string>;
    updatedAt: bigint;
    metaTitle: string;
    excerpt: string;
} {
    return {
        id: value.id,
        metaDescription: value.metaDescription,
        status: value.status,
        title: value.title,
        content: value.content,
        publishDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.publishDate)),
        featuredImage: value.featuredImage,
        createdAt: value.createdAt,
        slug: value.slug,
        tags: value.tags,
        updatedAt: value.updatedAt,
        metaTitle: value.metaTitle,
        excerpt: value.excerpt
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    couponCode: [] | [string];
    paymentMethod: _PaymentMethod;
    userId: Principal;
    discountAmount: bigint;
    createdAt: bigint;
    totalAmount: bigint;
    address: _Address;
    stripePaymentId: [] | [string];
    items: Array<_CartItem>;
}): {
    id: bigint;
    status: OrderStatus;
    couponCode?: string;
    paymentMethod: PaymentMethod;
    userId: Principal;
    discountAmount: bigint;
    createdAt: bigint;
    totalAmount: bigint;
    address: Address;
    stripePaymentId?: string;
    items: Array<CartItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n25(_uploadFile, _downloadFile, value.status),
        couponCode: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.couponCode)),
        paymentMethod: from_candid_PaymentMethod_n27(_uploadFile, _downloadFile, value.paymentMethod),
        userId: value.userId,
        discountAmount: value.discountAmount,
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        address: from_candid_Address_n29(_uploadFile, _downloadFile, value.address),
        stripePaymentId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.stripePaymentId)),
        items: value.items
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    street: string;
    country: string;
    gstNumber: [] | [string];
    city: string;
    postalCode: string;
    state: string;
}): {
    street: string;
    country: string;
    gstNumber?: string;
    city: string;
    postalCode: string;
    state: string;
} {
    return {
        street: value.street,
        country: value.country,
        gstNumber: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.gstNumber)),
        city: value.city,
        postalCode: value.postalCode,
        state: value.state
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    supplierContact: string;
    lowStockThreshold: bigint;
    purchaseCost: bigint;
    expiryDate: [] | [bigint];
    supplierName: string;
    lastUpdated: bigint;
    productId: string;
    incomingStock: bigint;
    reservedStock: bigint;
    batchNumber: string;
    currentStock: bigint;
    damagedStock: bigint;
}): {
    supplierContact: string;
    lowStockThreshold: bigint;
    purchaseCost: bigint;
    expiryDate?: bigint;
    supplierName: string;
    lastUpdated: bigint;
    productId: string;
    incomingStock: bigint;
    reservedStock: bigint;
    batchNumber: string;
    currentStock: bigint;
    damagedStock: bigint;
} {
    return {
        supplierContact: value.supplierContact,
        lowStockThreshold: value.lowStockThreshold,
        purchaseCost: value.purchaseCost,
        expiryDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.expiryDate)),
        supplierName: value.supplierName,
        lastUpdated: value.lastUpdated,
        productId: value.productId,
        incomingStock: value.incomingStock,
        reservedStock: value.reservedStock,
        batchNumber: value.batchNumber,
        currentStock: value.currentStock,
        damagedStock: value.damagedStock
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    minCartValue: bigint;
    active: boolean;
    discountValue: bigint;
    expiresAt: [] | [bigint];
    code: string;
    createdAt: bigint;
    discountType: string;
    usedCount: bigint;
    description: string;
    maxUses: bigint;
}): {
    id: string;
    minCartValue: bigint;
    active: boolean;
    discountValue: bigint;
    expiresAt?: bigint;
    code: string;
    createdAt: bigint;
    discountType: string;
    usedCount: bigint;
    description: string;
    maxUses: bigint;
} {
    return {
        id: value.id,
        minCartValue: value.minCartValue,
        active: value.active,
        discountValue: value.discountValue,
        expiresAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.expiresAt)),
        code: value.code,
        createdAt: value.createdAt,
        discountType: value.discountType,
        usedCount: value.usedCount,
        description: value.description,
        maxUses: value.maxUses
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    processing: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "processing" in value ? OrderStatus.processing : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cod: null;
} | {
    stripe: null;
}): PaymentMethod {
    return "cod" in value ? PaymentMethod.cod : "stripe" in value ? PaymentMethod.stripe : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n44(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminCoupon>): Array<AdminCoupon> {
    return value.map((x)=>from_candid_AdminCoupon_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminTask>): Array<AdminTask> {
    return value.map((x)=>from_candid_AdminTask_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Array<BlogPost> {
    return value.map((x)=>from_candid_BlogPost_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n23(_uploadFile, _downloadFile, x));
}
function to_candid_Address_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Address): _Address {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_AdminCoupon_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminCoupon): _AdminCoupon {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_AdminTask_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminTask): _AdminTask {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_BlogPost_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPost): _BlogPost {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_CreateOrderInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderInput): _CreateOrderInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_InventoryItem_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryItem): _InventoryItem {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_ProductFilter_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    metaDescription: string;
    status: string;
    title: string;
    content: string;
    publishDate?: bigint;
    featuredImage: string;
    createdAt: bigint;
    slug: string;
    tags: Array<string>;
    updatedAt: bigint;
    metaTitle: string;
    excerpt: string;
}): {
    id: string;
    metaDescription: string;
    status: string;
    title: string;
    content: string;
    publishDate: [] | [bigint];
    featuredImage: string;
    createdAt: bigint;
    slug: string;
    tags: Array<string>;
    updatedAt: bigint;
    metaTitle: string;
    excerpt: string;
} {
    return {
        id: value.id,
        metaDescription: value.metaDescription,
        status: value.status,
        title: value.title,
        content: value.content,
        publishDate: value.publishDate ? candid_some(value.publishDate) : candid_none(),
        featuredImage: value.featuredImage,
        createdAt: value.createdAt,
        slug: value.slug,
        tags: value.tags,
        updatedAt: value.updatedAt,
        metaTitle: value.metaTitle,
        excerpt: value.excerpt
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    couponCode?: string;
    paymentMethod: PaymentMethod;
    address: Address;
    stripePaymentId?: string;
    items: Array<CartItem>;
}): {
    couponCode: [] | [string];
    paymentMethod: _PaymentMethod;
    address: _Address;
    stripePaymentId: [] | [string];
    items: Array<_CartItem>;
} {
    return {
        couponCode: value.couponCode ? candid_some(value.couponCode) : candid_none(),
        paymentMethod: to_candid_PaymentMethod_n19(_uploadFile, _downloadFile, value.paymentMethod),
        address: to_candid_Address_n21(_uploadFile, _downloadFile, value.address),
        stripePaymentId: value.stripePaymentId ? candid_some(value.stripePaymentId) : candid_none(),
        items: value.items
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    street: string;
    country: string;
    gstNumber?: string;
    city: string;
    postalCode: string;
    state: string;
}): {
    street: string;
    country: string;
    gstNumber: [] | [string];
    city: string;
    postalCode: string;
    state: string;
} {
    return {
        street: value.street,
        country: value.country,
        gstNumber: value.gstNumber ? candid_some(value.gstNumber) : candid_none(),
        city: value.city,
        postalCode: value.postalCode,
        state: value.state
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    minCartValue: bigint;
    active: boolean;
    discountValue: bigint;
    expiresAt?: bigint;
    code: string;
    createdAt: bigint;
    discountType: string;
    usedCount: bigint;
    description: string;
    maxUses: bigint;
}): {
    id: string;
    minCartValue: bigint;
    active: boolean;
    discountValue: bigint;
    expiresAt: [] | [bigint];
    code: string;
    createdAt: bigint;
    discountType: string;
    usedCount: bigint;
    description: string;
    maxUses: bigint;
} {
    return {
        id: value.id,
        minCartValue: value.minCartValue,
        active: value.active,
        discountValue: value.discountValue,
        expiresAt: value.expiresAt ? candid_some(value.expiresAt) : candid_none(),
        code: value.code,
        createdAt: value.createdAt,
        discountType: value.discountType,
        usedCount: value.usedCount,
        description: value.description,
        maxUses: value.maxUses
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featured?: boolean;
    minRating?: number;
    sortBy?: string;
    maxPrice?: bigint;
    category?: string;
    minPrice?: bigint;
    searchQuery?: string;
}): {
    featured: [] | [boolean];
    minRating: [] | [number];
    sortBy: [] | [string];
    maxPrice: [] | [bigint];
    category: [] | [string];
    minPrice: [] | [bigint];
    searchQuery: [] | [string];
} {
    return {
        featured: value.featured ? candid_some(value.featured) : candid_none(),
        minRating: value.minRating ? candid_some(value.minRating) : candid_none(),
        sortBy: value.sortBy ? candid_some(value.sortBy) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none(),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none()
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    supplierContact: string;
    lowStockThreshold: bigint;
    purchaseCost: bigint;
    expiryDate?: bigint;
    supplierName: string;
    lastUpdated: bigint;
    productId: string;
    incomingStock: bigint;
    reservedStock: bigint;
    batchNumber: string;
    currentStock: bigint;
    damagedStock: bigint;
}): {
    supplierContact: string;
    lowStockThreshold: bigint;
    purchaseCost: bigint;
    expiryDate: [] | [bigint];
    supplierName: string;
    lastUpdated: bigint;
    productId: string;
    incomingStock: bigint;
    reservedStock: bigint;
    batchNumber: string;
    currentStock: bigint;
    damagedStock: bigint;
} {
    return {
        supplierContact: value.supplierContact,
        lowStockThreshold: value.lowStockThreshold,
        purchaseCost: value.purchaseCost,
        expiryDate: value.expiryDate ? candid_some(value.expiryDate) : candid_none(),
        supplierName: value.supplierName,
        lastUpdated: value.lastUpdated,
        productId: value.productId,
        incomingStock: value.incomingStock,
        reservedStock: value.reservedStock,
        batchNumber: value.batchNumber,
        currentStock: value.currentStock,
        damagedStock: value.damagedStock
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    assignedTo?: string;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    notes: string;
    category: string;
    priority: string;
}): {
    id: string;
    title: string;
    assignedTo: [] | [string];
    createdAt: bigint;
    completed: boolean;
    dueDate: [] | [bigint];
    description: string;
    notes: string;
    category: string;
    priority: string;
} {
    return {
        id: value.id,
        title: value.title,
        assignedTo: value.assignedTo ? candid_some(value.assignedTo) : candid_none(),
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description,
        notes: value.notes,
        category: value.category,
        priority: value.priority
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cod: null;
} | {
    stripe: null;
} {
    return value == PaymentMethod.cod ? {
        cod: null
    } : value == PaymentMethod.stripe ? {
        stripe: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    processing: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.processing ? {
        processing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
